# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dcs.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dcs(object):
    def setupUi(self, Dcs):
        Dcs.setObjectName("Dcs")
        Dcs.resize(556, 392)
        Dcs.setMaximumSize(QtCore.QSize(556, 392))
        Dcs.setAutoFillBackground(False)
        Dcs.setStyleSheet("background-color: #8798A6;")
        self.tabWidget = QtWidgets.QTabWidget(Dcs)
        self.tabWidget.setGeometry(QtCore.QRect(180, 20, 371, 361))
        self.tabWidget.setStyleSheet("QTab {\n"
"    color: #fff;\n"
"    background-color: #2B333A;\n"
"    border-radius: 8px;\n"
"}\n"
"QTab:pressed {\n"
"    background-color: #33424D ;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.frame = QtWidgets.QFrame(Dcs)
        self.frame.setGeometry(QtCore.QRect(0, 0, 171, 401))
        self.frame.setStyleSheet("background-color: #2B333A;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 370, 51, 16))
        self.label.setStyleSheet("color: #fff;")
        self.label.setObjectName("label")

        self.retranslateUi(Dcs)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dcs)

    def retranslateUi(self, Dcs):
        _translate = QtCore.QCoreApplication.translate
        Dcs.setWindowTitle(_translate("Dcs", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dcs", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dcs", "Tab 2"))
        self.label.setText(_translate("Dcs", "Dcs v1.0.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dcs = QtWidgets.QDialog()
    ui = Ui_Dcs()
    ui.setupUi(Dcs)
    Dcs.show()
    sys.exit(app.exec_())
